version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./server:/server
    environment:
      PGDATA: $POSTGRES_DATA
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
  web:
    build: .
    environment:
      MIX_ENV: $MIX_ENV
      ELIXIR_SECRET: $ELIXIR_SECRET
    command: mix phoenix.server
    user: $DOCKER_USER_ID:$DOCKER_USER_GROUP_ID
    volumes:
      - ./server:/server
    ports:
      - "$PORT_HTTP:4000"
    restart: always
    depends_on:
      - db
